-- Ejecuta este archivo en Supabase > SQL Editor.

create table if not exists public.vehiculos_buscados (
    id bigint generated by default as identity primary key,
    placa text not null unique,
    motivo text not null default 'otro',
    prioridad integer not null default 1 check (prioridad between 1 and 3),
    color text,
    marca text,
    modelo text,
    anio integer,
    registrado_por text,
    activo boolean not null default true,
    creado_en timestamptz not null default now()
);

create index if not exists idx_vehiculos_buscados_placa
on public.vehiculos_buscados (placa);

create table if not exists public.detecciones (
    id bigint generated by default as identity primary key,
    fecha_hora timestamptz not null default now(),
    placa text not null,
    color text default 'Pendiente',
    confianza double precision,
    camara_id text,
    ubicacion text
);

alter table public.detecciones
    add column if not exists confianza double precision;

alter table public.detecciones
    add column if not exists camara_id text;

alter table public.detecciones
    add column if not exists ubicacion text;

create index if not exists idx_detecciones_placa
on public.detecciones (placa);

create index if not exists idx_detecciones_fecha_hora
on public.detecciones (fecha_hora desc);

-- Para desarrollo con la clave anon.
-- En producción conviene crear políticas más restrictivas.
alter table public.detecciones enable row level security;
alter table public.vehiculos_buscados enable row level security;

drop policy if exists "Lectura pública de detecciones" on public.detecciones;
create policy "Lectura pública de detecciones"
on public.detecciones for select
using (true);

drop policy if exists "Inserción pública de detecciones" on public.detecciones;
create policy "Inserción pública de detecciones"
on public.detecciones for insert
with check (true);

drop policy if exists "Lectura pública de vehículos buscados"
on public.vehiculos_buscados;
create policy "Lectura pública de vehículos buscados"
on public.vehiculos_buscados for select
using (true);
